### ISSUE TITLE
The data related to an image is not transferred

### ISSUE THREAD

**Issue by Anthere** [openzim/wikifundi#54] opened 2018-06-25 11:13 UTC
For example : http://wikifundi-fr.openzim.org/wiki/Fichier:WikiFundi_A5_flyer_French.pdf
https://commons.wikimedia.org/wiki/File:WikiFundi_A5_flyer_French.pdf?uselang=fr

Does not contain 
* description
* date
* source
* auteur

Was already reported in version 1

**Comment by kelson42** [comment] 2018-06-26 05:21
Yes, duplicate of https://github.com/openzim/wikifundi/issues/12

**Closed by kelson42** 2018-06-26 05:21 UTC
